<?php

declare(strict_types=1);

/**
 * Generate README.md from the docs in docs/. The docs are the single source of
 * truth. Run after editing anything under docs/:
 *
 *     php scripts/gen-readme.php   (or: composer gen-readme)
 *
 * CI (.github/workflows/tests.yml) re-runs it and asserts no diff. Idempotent.
 */

const OWNER = 'shipeasy-ai';
const REPO = 'sdk-php';
const PACKAGIST = 'shipeasy/shipeasy';
const BLOB = 'https://github.com/' . OWNER . '/' . REPO . '/blob/main';
const PAGES_SITE = 'https://' . OWNER . '.github.io/' . REPO;

$ROOT = dirname(__DIR__);
$DOCS = $ROOT . '/docs';

$pageOrder = [
    'overview', 'installation', 'configuration', 'flags', 'configs',
    'killswitches', 'experiments', 'i18n', 'error-reporting', 'testing',
    'openfeature', 'advanced', 'admin-api',
];
$pageTitle = [
    'overview' => 'Overview', 'installation' => 'Installation', 'configuration' => 'Configuration',
    'flags' => 'Feature flags', 'configs' => 'Dynamic configs', 'killswitches' => 'Kill switches',
    'experiments' => 'Experiments', 'i18n' => 'Internationalization', 'error-reporting' => 'Error reporting',
    'testing' => 'Testing', 'openfeature' => 'OpenFeature', 'advanced' => 'Advanced',
    'admin-api' => 'Admin API client',
];
$pageBlurb = [
    'overview' => 'The `configure()` + `new Client($user)` model.',
    'installation' => 'Install, frameworks (Laravel / Symfony / WordPress), `configure()` wiring.',
    'configuration' => 'Keys, `attributes`, fetch-once-per-request, every option.',
    'flags' => '`getFlag`, `getFlagDetail`, defaults.',
    'configs' => '`getConfig`, typed decode, defaults.',
    'killswitches' => '`getKillswitch`, named switches.',
    'experiments' => '`universe()->assign()`, `track`.',
    'i18n' => 'SSR bootstrap + i18n loader tags.',
    'error-reporting' => '`see()` structured error reporting.',
    'testing' => '`configureForTesting` / `configureForOffline`, overrides.',
    'openfeature' => '`ShipeasyProvider` (OpenFeature provider).',
    'advanced' => 'Anon-id middleware, private attributes, sticky bucketing, SSR.',
    'admin-api' => 'Optional `Shipeasy\Admin\AdminClient` for administering resources (generated from the OpenAPI spec).',
];

function read_doc(string $rel): string
{
    global $DOCS;
    return file_get_contents($DOCS . '/' . $rel);
}

function first_code(string $md, string $lang): string
{
    if (preg_match('/```' . preg_quote($lang, '/') . '\n(.*?)```/s', $md, $m)) {
        return rtrim($m[1]);
    }
    return '';
}

function lead_paragraph_md(string $md): string
{
    $out = [];
    $started = false;
    foreach (explode("\n", $md) as $ln) {
        if (!$started) {
            $started = str_starts_with($ln, '# ');
            continue;
        }
        $s = trim($ln);
        if ($s === '') {
            if ($out) {
                break;
            }
            continue;
        }
        if (preg_match('/^[#`>|\-<]/', $s)) {
            if ($out) {
                break;
            }
            continue;
        }
        $out[] = $s;
    }
    return trim(preg_replace('/\s+/', ' ', implode(' ', $out)));
}

function absolutize(string $text): string
{
    return preg_replace_callback('/\]\(([\w.\/-]+?\.md)(#[\w-]+)?\)/', function ($m) {
        if (str_starts_with($m[1], '/')) {
            return $m[0];
        }
        return '](' . BLOB . '/docs/pages/' . $m[1] . ($m[2] ?? '') . ')';
    }, $text);
}

function lead_paragraph(string $md): string
{
    $s = lead_paragraph_md($md);
    $s = preg_replace('/`([^`]+)`/', '$1', $s);
    $s = preg_replace('/\*\*(.+?)\*\*/', '$1', $s);
    $s = preg_replace('/\[(.+?)\]\([^)]*\)/', '$1', $s);
    return trim($s);
}

$manifest = json_decode(read_doc('manifest.json'), true);
$sdk = $manifest['sdk'];

$install = first_code(read_doc('pages/installation.md'), 'bash') ?: 'composer require ' . PACKAGIST;
$quickstart = first_code(read_doc('pages/overview.md'), 'php');
$testingMd = read_doc('pages/testing.md');
$testingLead = absolutize(lead_paragraph_md($testingMd));
$testingCode = first_code($testingMd, 'php');

$rows = [];
foreach ($pageOrder as $key) {
    $title = $pageTitle[$key] ?? $key;
    $blurb = $pageBlurb[$key] ?? lead_paragraph(read_doc($manifest['pages'][$key]));
    if (strlen($blurb) > 90) {
        $blurb = rtrim(substr($blurb, 0, 87)) . '…';
    }
    $rows[] = "| [$title](" . BLOB . "/docs/pages/$key.md) | $blurb |";
}
$docsTable = implode("\n", $rows);

$readme = <<<MD
<!--
  This file is GENERATED by scripts/gen-readme.php from docs/.
  Do NOT edit by hand — edit the docs, then run: php scripts/gen-readme.php
-->

# shipeasy/shipeasy (PHP)

[![Tests](https://github.com/OWNERX/REPOX/actions/workflows/tests.yml/badge.svg)](https://github.com/OWNERX/REPOX/actions/workflows/tests.yml)
[![Packagist Version](https://img.shields.io/packagist/v/PKGX.svg)](https://packagist.org/packages/PKGX)
[![PHP Version](https://img.shields.io/packagist/dependency-v/PKGX/php.svg)](https://packagist.org/packages/PKGX)

Server SDK for [Shipeasy](https://shipeasy.ai) — **feature flags, dynamic configs,
kill switches, A/B experiments, and metric tracking** for PHP. Server-key only;
never embed in a browser.

> 📚 **Full documentation:** **<PAGESX/>** — also browsable under
> [`docs/`](BLOBX/docs). This README is generated from those docs.

## 🤖 Using an AI agent?

This SDK ships an installable **agent skill** — a copy-paste-ready guide to
`configure()` + `new Client(\$user)`, testing, experiments, error reporting, and
more, with links the agent can pull for deeper docs:

- **Skill:** [`docs/skill/SKILL.md`](BLOBX/docs/skill/SKILL.md) · raw:
  `PAGESX/skill/SKILL.md`
- **Install it** (ships with the package — no network):
  `vendor/bin/shipeasy-skill install` → `.claude/skills/shipeasy-SDKX/SKILL.md`
  (or via the Shipeasy CLI: `shipeasy docs skill --sdk SDKX --install`)

**Humans:** you can copy that skill straight into your own project's agent skills
directory so your coding agent always uses the correct Shipeasy patterns. Every
doc page and snippet is also fetchable by URL — start from the manifest at
`PAGESX/manifest.json`.

## Install

```bash
INSTALLX
```

Per-framework setup (Laravel / Symfony / WordPress) and the anon-id middleware are
on the [Installation](BLOBX/docs/pages/installation.md) page.

## Quickstart — `configure()` once, then `new Client(\$user)` per request

```php
QUICKX
```

Constructing `new Client(\$user)` before `configure()` throws.

## Documentation

| Page | What |
| --- | --- |
TABLEX

Copy-paste snippets live under [`docs/snippets/`](BLOBX/docs/snippets)
(release · metrics · i18n · ops); an installable agent skill is at
[`docs/skill/SKILL.md`](BLOBX/docs/skill/SKILL.md).

## Testing

TESTLEADX

```php
TESTCODEX
```

More — the on-the-spot override helpers and a working example snapshot file — on
the [Testing](BLOBX/docs/pages/testing.md) page.

## License

See [LICENSE](BLOBX/LICENSE). Evaluation is tested against the cross-language
MurmurHash3 vectors in `experiment-platform/04-evaluation.md`.

MD;

$readme = strtr($readme, [
    'OWNERX' => OWNER,
    'REPOX' => REPO,
    'PKGX' => PACKAGIST,
    'PAGESX' => PAGES_SITE,
    'BLOBX' => BLOB,
    'SDKX' => $sdk,
    'INSTALLX' => $install,
    'QUICKX' => $quickstart,
    'TABLEX' => $docsTable,
    'TESTLEADX' => $testingLead,
    'TESTCODEX' => $testingCode,
]);

file_put_contents($ROOT . '/README.md', $readme);
fwrite(STDOUT, 'Wrote README.md (' . strlen($readme) . " bytes) from " . count($pageOrder) . " doc pages.\n");
